name: GNU Make

on: [push]

jobs:
    build:
        runs-on: ubuntu-24.04
        strategy:
            matrix:
                python-version: ["3.11", "3.12", "3.13"]
        steps:
            -
                name: Checkout project
                uses: actions/checkout@v5                                       # https://github.com/actions/checkout
                with:
                    path: main
                    submodules: true
            -
                name: Set up Python ${{ matrix.python-version }}
                uses: actions/setup-python@v6                                   # https://github.com/actions/setup-python
                with:
                    cache: pip
                    cache-dependency-path: |
                        main/requirements.txt
                        main/fortranlib/requirements.txt
                    python-version: ${{ matrix.python-version }}
            -
                name: Install FORTRAN dependencies
                run: |
                    sudo apt-get update
                    sudo apt-get install libhdf5-dev
                    sudo apt-get install hdf5-helpers
            -
                name: Install Python ${{ matrix.python-version }} dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install -r main/requirements.txt
                    pip install -r main/fortranlib/requirements.txt
            -
                name: List programs
                run: |
                    echo "::notice $(which gmake)"
                    echo "::notice $(which h5fc)"
                    echo "::notice $(which pip)"
                    echo "::notice $(which python)"
            -
                name: Compile the FORTRAN code
                run: |
                    cd main
                    gmake -r -C src FC=`which h5fc` PYTHON3=`which python` compile
